### PR TITLE
Small message fixup

### PR DESCRIPTION
**Pull request by Mizux**

### CODE REVIEW

**Comment by Mizux** [comment]
still have issues to extract my data :(

BTW thanks for this project !

**Comment by smx-smx** [comment]
Oh wow, someone else has this game!

Thanks for the patch, and feel free to contact me via mail (or hangouts or whatever) if you have further questions.

I have made other experiments with the game files
KeraView

**Comment by smx-smx** [comment]
There was a typo in a stat() call.
I fixed that, and migrated the codebase to C++ too

Try it now

**Comment by Mizux** [comment]
Hi, just finish my C++ port on my side too ^^

Unfortunately it doesn't work -_-;
You can take a look at it here: https://github.com/Mizux/kunp

**Comment by Mizux** [comment]
Dumb question, which os did you use ? currently I tried to run it on wine without success ^^;

ps: irc freenode user `mizux` or discord ?

**Pull request merged**
